### ISSUE TITLE
Hide additional info under spoiler tag

### ISSUE THREAD

**Issue by freeseacher** [fboender/ansible-cmdb#103]
HI!
probably most discussionable enhancement hide all extended info that follows brief table under `spoliers`, so user have to click to open it. 

I think there is really a lot of useless info that can't be used directly but only can be usefull from time to time. For example interface detail. 
Maybe it will be better to see all info in a collapsed way by default 
```
host ->
  general ->
  groups ->
  hardware ->
  ....
```
of cause there should be a button to unfold everything and fold everything back

**Comment by fboender** [comment]
There's already issue #14 for this. Take a look, I think it's the same thing you want. It's a feature I really want to implement, but haven't had the time for yet. It's slightly problematic due to the way I display the host name in the top header bar. I'll give implementing collapsing sections another go though.

I'm going to close this issue, since I think it's the same as #14. If not, please reopen this issue and elaborate on how you think it's different from #14.

Thanks!
