### ISSUE TITLE
html_fancy does not support column?

### ISSUE THREAD

**Issue by silviuvulcan** [fboender/ansible-cmdb#105]
According to the documentation it should, but if I produce a file like this:

````
 ansible-cmdb -t html_fancy --columns name out/
````

I still get the full table. I can see the css property of `col-invisible` but at least in my browser (latest google chrome) it does nothing...

**Comment by silviuvulcan** [comment]
UPDATE:

Ironically enough it works in internet explorer 11, doesn't work in firefox 43.0.4 either.

**Comment by fboender** [comment]
Hi Silviu!

The first issue (works in IE, not in Firefox) is probably because you opened an earlier version with more columns in Firefox. The shown columns are remembered, so it shows more than just the "name" column. You probably hadn't opened the file in IE previously, so it had no memory about columns already being shown.

But really, html_fancy shouldn't even *include* the columns in the output in the first place. So this is still a bug.

The second issue ("Refused to load the script") is probably due to serving the output from a webserver with strict "Content-Security" header. You should reconfigure the web server so that it allows inclusion from https://code.jquery.com/.

I'll have a look at the columns problem as soon as possible.

**Comment by silviuvulcan** [comment]
Thank you, I was using it from jenkins and I didn't realize that jenkins sets a strict Content-Security. Now that jquery loads the collumns are hidden in the table. (They can be opened using the buttons above)

**Comment by fboender** [comment]
Good to hear!

> But really, html_fancy shouldn't even include the columns in the output in the first place. So this is still a bug.

I was wrong about this. From the source it's obvious that using `columns` is just supposed to set the initial state to "hidden" for columns not listed. It's actually quite difficult to only include the columns specified in the output, so if your need is served by the current implementation, I'm going to take the easy way out and keep it like it is ;-)

Thanks for the report!
