### ISSUE TITLE
NFS/CIFS-Shares

### ISSUE THREAD

**Issue by starflighter** [fboender/ansible-cmdb#116]
Hi,
is it possible to expand the overview of the website (html-file) with information about nfs and cifs-shares like the section disks?

Thanks,
starflighter

**Comment by fboender** [comment]
Hey starflighter!

I assume NFS and CIFS information shows up as "mounts" in the "Storage" sub-section of the host details? I could add a column with the Mounts to the host overview. Which exact information would you like to see in it?

**Comment by starflighter** [comment]
I would like to see the Name of the mount and the size, like this:
![grafik](https://cloud.githubusercontent.com/assets/23389327/26723019/c47f1660-4792-11e7-997b-7fe56f77c899.png)

**Comment by starflighter** [comment]
First thank you for your work.
Is it possible to filter with jsonxs like "if fstype == nfs, show device and size"?

**Comment by fboender** [comment]
I'm afraid that kind of logic isn't possible with jsonxs. Perhaps I should add an option to the custom columns for rendering a small piece of templating for each column. Something like this:

    {
        "title": "NFS Shares",
        "id": "nfsshares",
        "sType": "html",
        "visible": true,
        "template": """
          <li>
          % for fs in facts['mounts']:
            % if fs['type'] == 'nfs':
              <ul>${fs['name']}: ${fs['size']}</ul>
          </li>
        """
    }

**Comment by fboender** [comment]
I've made a few small changes in the custom columns functionality:

* The custom columns file is no longer JSON, but rather Python code, so that multi-line strings are properly supported. Not much changes, as Python code is *almost* backwards compatible with JSON. The only thing that's different is that `true` and `false` should be capitalized now. See https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-columns for a new example configuration file.
* There is now support for template fragments for rendering columns in addition to the `jsonxs` method. Template fragments are more powerful, but also a bit more complicated. Again, see the ReadTheDocs documentation for an example.

I'll be releasing a new version of Ansible-cmdb soon. If you want to try it in the meantime, you'll have to use the git `master` branch.

From the documentation, do you think you'll be able to manage writing a template fragment to get the columns you'd like to see, or do you need some help with that?

**Comment by fboender** [comment]
v1.29 of ansible-cmdb has been released, which includes the new custom columns functionality.

I'm going to close this issue. If you still need some help with creating the columns using the new `--cust-cols` method, please don't hesitate to re-open this issue!

**Comment by eldho-varghese** [comment]
Hi

I would like to display the NFS share name in the CMBD columns. Would you be able to correct the below coding ?

 {"title": "NFS Share",     "id": "nfsshares",     "func": col_nfsshare,       "sType": "string", "visible": False},

<%def name="col_nfsshare(host, **kwargs)">
  ${jsonxs(host, 'nfsshares', default='')}

 <% nfsshares = jsonxs(host, 'ansible_facts.ansible_mounts', default=[])%>
  % for fs in jsonxs(host, 'ansible_facts.ansible_mounts', default=[]):
     <li>
        % if fs['type'] == 'nfs':
          <ul>${fs['name']}: ${fs['size']}</ul>
        % endif
     % endfor
      </li>
</%def>
