### ISSUE TITLE
Partitions < 1GB are ignored

### ISSUE THREAD

**Issue by muffl0n** [fboender/ansible-cmdb#12]
I'm not quite sure if it's a good idea to just ignore partitions that are smaller than 1GB. Or, even worse, have < 1GB space left!

What was the intention behind the decision for that? Before I submit a PR to change that I'd like to understand why it is that way. :)

**Comment by fboender** [comment]
The idea was to exclude "non interesting" mount points under some distributions such as /dev, /var/lock. It seems that Ansible doesn't include them anyway, so it's not a problem to include mount points smaller than 1gb. There should still be check for at least a size of 1 byte available, otherwise ansible-cmdb will run into division by zero errors.

Btw, ansible-cmdb does not exclude mount points with less than 1 GB free space, *only* mount points with less than 1 GB *total* space

**Comment by muffl0n** [comment]
Okay, maybe I misinterpreted the check on size_total and size_available. 

I way already thinking about a way to optimize the display of "Disk avail" and "Disk total" because currently it just get's mixed up and you don't know to which partition what size belongs. So the numbers are quite useless. Only the bars in "Disk usage" give you a good idea about the partitions.
![size](https://cloud.githubusercontent.com/assets/927904/9272196/57df4ed0-4280-11e5-8e05-f0b529524ddb.png)

**Comment by muffl0n** [comment]
My proposal would be to remove "Disk total" and "Disk avail" and merge them with the "Disk usage" column:
![size](https://cloud.githubusercontent.com/assets/927904/9272307/4638b44a-4281-11e5-9b41-5c21c64fd3ba.png)

**Comment by fboender** [comment]
That looks quite nice! Maybe make the font for the sizes slightly smaller so it's easier to differentiate between the mount point and the sizes?

**Comment by muffl0n** [comment]
I tried my best :)

![size](https://cloud.githubusercontent.com/assets/927904/9272573/324d201c-4284-11e5-8f14-6b5250d0df1c.png)

**Comment by muffl0n** [comment]
We are still ignoring partitions with a total size < 1GB with that:
```
    % if i['size_total']/1048576000 > 1:
```
Maybe just ditch that line?

**Comment by fboender** [comment]
Looks great Sven. I've merged the changes.

I've also committed a change so that disks < 1GB are shown.

Thanks for your PR and feedback!
