### ISSUE TITLE
Extract group name from group_vars/file without extension

### ISSUE THREAD

**Issue by nymous** [fboender/ansible-cmdb#130]
When using a `group_vars` folder, the groupname to which variables read from a file are attached is the file name (see https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L164).
That means that if the file is called `webserver.yml`, ansible_cmdb will add the variables in it to any host belonging to the group `webserver.yml` instead of `webserver`.

It seems to also be the case for host_vars, as I can read here https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L121, but I didn't test it.

**Comment by fboender** [comment]
Looks like a bug, since the Ansible documentation says:

> /etc/ansible/group_vars/raleigh # can optionally end in '.yml', '.yaml', or '.json'

I probably missed this when reading the documentation.

> It seems to also be the case for host_vars, as I can read here https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L121, but I didn't test it.

The official Ansible documentation doesn't explicitly specify that it does, but it seems a reasonable assumption. 

I've just pushed a new commit to master that fixes these issues. Some testing shows that it's working for me. Can you verify?

Thank you for the excellent bug report, the references to the actual code and the investigation into the host_vars implementation having the same problem!

**Comment by nymous** [comment]
I did verify it (last week actually), and it is working for me too.

Closing the issue, thanks for your work!
