### ISSUE TITLE
Attach group_vars from all.yml to all hosts

### ISSUE THREAD

**Issue by nymous** [fboender/ansible-cmdb#131]
The file `group_vars/all` contains variables that are used for all hosts, since they all belong implicitly to it.

I think that ansible_cmd is instead trying to attach the variables to any host explicitly added to the group `all`.

I have tested this with
```
inventories/
  - group_vars/
    - all
    - webservers
```
variables defined in `all` are not visible in 'Custom variables', but when moved to `webservers` they are visible.

(Note: removed file extensions from my example since they are incorrectly used, see #130)

**Comment by fboender** [comment]
I've pushed a commit to master that handles the special cases of 'all' group_vars and host_vars. There's still an issue with variable precedence that eludes me. Currently, 'all' variables override host and group specific variables. Once I tackle this issue, I'll update this ticket.

**Comment by fboender** [comment]
Host and group specific variables are no longer overridden by 'all' variables in the latest commit to master. There will probably still be some gotcha's regarding variable precedence though. Displaying variables in the CMDB was always considered as a little 'extra', and shouldn't be relied upon too much to reflect actual variables used when running ansible (since they can always be overridden in a dozen other places that ansible-cmdb cannot reach).

**Comment by nymous** [comment]
It is working for me (at least for the simple use case I have).

Thank you!
