### ISSUE TITLE
Secure data are not hidden in the report

### ISSUE THREAD

**Issue by egormin** [fboender/ansible-cmdb#148]
All my logins and passwords are visible in the report.

![image](https://user-images.githubusercontent.com/17744515/35615176-6b5c2e24-0682-11e8-962e-215f3036d860.png)

Obviously, I do not keep these passwords in the inventory file, I use content replacer during the execution process. Initially, my password looks like "myPassword" and it changes by Jenkins or TeamCity. 
I was confused when noticed that all my sensitive data are visible.
I found the way how we can exclude some columns, however, I didn't find the way how we can exclude these fields or mask it in the report.

**Comment by fboender** [comment]
Hi egormin!

If you're seeing this, then the passwords *must* be stored somewhere in plain text, on disk, at some time. That's not a good idea. You should use SSH keys or type in the password manually when connecting. For other non-connect secrets (such as application or user passwords) you should store them using ansible vault (http://docs.ansible.com/ansible/2.4/vault.html).

It's not possible for ansible-cmdb to guess which of the variables are sensitive and which aren't. If it's available in plain text, then it should be assumed that it's not sensitive (otherwise, why would it be available in plain text?).

So I'm afraid I can't fix this, and I suggest you look at how it's possible that this information ended up in Ansible-cmdb and fix the issue there. I think SSH keys are the solution here. Not only are they much more secure, they're also easier to use. There's a nice tutorial available (here)[https://www.digitalocean.com/community/tutorials/ssh-essentials-working-with-ssh-servers-clients-and-keys]

With kind regards,

Ferry
