### ISSUE TITLE
-i option requires a file. directories not supported

### ISSUE THREAD

**Issue by palmerit** [fboender/ansible-cmdb#15]
First,    thanks for the awesome tool.  I've been looking for a way to visualize my infrastructure for a while now.  I love this idea.

On to the issue:
ansible allows "inventory" to point at a directory, it then parses all files in that directory to create the inventory list. As such, I've broken my hosts into a directory like so:

hosts/
hosts/development
hosts/test
hosts/staging
hosts/production

and in ansible.cfg, I have:
inventory = ./hosts

The problem is,  ansible-cmdb doesn't allow me to specify -i as a directory,   or multiple -i statements (one per file),  thus the resulting html output is partial and incomplete.

**Comment by fboender** [comment]
Hey Jeff,

I've pushed a commit to the master branch that should fix this issue. It will be included in the next release. If you are familiar with git, you could check out the master branch and test if it works. Otherwise, you'll have to wait until I release new packages (which shouldn't be long).

Thanks for your bug report!

Regards,

Ferry

**Comment by palmerit** [comment]
Ferry,

I have to applaud your responsiveness.   Nice response times.

I've issued a pull request #19 against this commit.  It seems as though a debug statement was inadvertently left in place.
