### ISSUE TITLE
Adding columns for custom facts

### ISSUE THREAD

**Issue by Diablo2050** [fboender/ansible-cmdb#171]
How can i add more columns to be filled out by custom facts ?

**Comment by fboender** [comment]
Hi Amr!

Adding custom columns required the creation of a custom template. I've documented how to do this on [ansible-cmdb.readthedocs.io](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-templates).

It's a bit involved, but I'm afraid adding columns isn't going to be easy one way or another, since there is no uniform way in which to address Ansible facts in anything but a full-fledged (templating) language.

I hope this is of some use!
