### ISSUE TITLE
SELinux not parsed properly on Red Hat 7

### ISSUE THREAD

**Issue by ZappedC64** [fboender/ansible-cmdb#175]
It does not appear that the SELinux configuration is parsed properly on Red Hat 7. This is what I see under Operating System:

SELinux?	{u'status': u'enabled', u'policyvers': 31, u'type': u'targeted', u'mode': u'enforcing', u'config_mode': u'enforcing'}

Hope this helps.

**Comment by fboender** [comment]
Hi ZappedC64!

This problem should be fixed in the ansible-cmdb master branch. Here's what it looks like:

![selinux](https://user-images.githubusercontent.com/2477515/44741672-137a5700-aafe-11e8-975b-8e8fee0ebe76.png)

I'm going to close this bug report. If you're still experiencing problems, please reopen this ticket!
