### ISSUE TITLE
index.html output not working outside the Server where ansible-cmdb installed

### ISSUE THREAD

**Issue by biabilal** [fboender/ansible-cmdb#176]
Hi, 

I have tried to use your project ansible-cmdb and was able to generate index.html along with my server details but the Webpage is not working as expected.
If I click on the tabs within my VM, they work fine. But if I export the index.html and relevant server files out of my VM then all the tabs are by default clicked/unclicked and it looks like a static Page. I am unable to filter out the data as TABS are not working.

Ansible-cmdb Version :: 1.28
Sample working URL:  https://rawgit.com/fboender/ansible-cmdb/master/example/html_fancy.html#

Attached Sample files for your reference.
[index.zip](https://github.com/fboender/ansible-cmdb/files/2329185/index.zip)

**Comment by fboender** [comment]
Hi biabilal!

This is to be expected and unfortunately there isn't much I can do about it. If you're using `local_js=1`, the Javascript resources required to display the page are read from local disk. This is required if you're opening the cmdb using a `file://cmdb.html` link, because modern browser do not allow you to load http/https resources from a `file://` origin. In your case, you're moving the files to a host that doesn't have the required javascript libraries because ansible-cmdb isn't installed.

The proper solution (if you don't want to install ansible-cmdb on the computer you're trying to view the output on) is to use `local_js=0` and host the resulting html file(s) on a webserver. This way, it will be using the `http://` or `https://` origin, and it can load javascript sources from a CDN. You could host the output on a Apache or Nginx server, or (if Python is installed) you can use Python to spin up a simple webserver:

    $ ls cmdb.html  # generated with -p local_js=0
    cmdb.html
    $ python3 -m http.server   # Use "-m SimpleHTTPServer" for python v2
    Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
    $ xdg-open http://0.0.0.0:8000/cmdb.html
    Created new window in existing browser session.
