### ISSUE TITLE
do you support the collection of physical machine assets in Windows system?

### ISSUE THREAD

**Issue by nondevops** [fboender/ansible-cmdb#225]
Hello, do you support the collection of physical machine assets in Windows system?

**Comment by fboender** [comment]
I'm not sure to be honest. I have no experience running ansible with windows machines. Ansible-cmdb merely uses the output of Ansible, so if Ansible supports physical machine assets, it should be possible to integrate those into ansible-cmdb. Maybe you'd have to do something with custom facts.

For now I'm going to close this issue, since it's not directly a thing with ansible-cmdb, but more with ansible, if I understood correctly. If that's incorrect, please reopen this issue or create a new one!
