### ISSUE TITLE
uploading to PyPI

### ISSUE THREAD

**Issue by shirou** [fboender/ansible-cmdb#23]
Thank you for creating great tool!

But why don't you upload to [PyPI](https://pypi.python.org/pypi)? From PyPI, we can install using widely used python package manager [pip](https://pip.pypa.io/en/stable/).

I would appreciate it if you could think with this matter.

**Comment by fboender** [comment]
Hey Shirou!

Thanks for the suggestion! I think I will upload to PyPi as using pip is quite convenient to install Python programs., It's currently not the highest priority so it might take a few days/weeks.

**Comment by fboender** [comment]
Hey!

I've tried to package up ansible-cmdb for PyPi, but have come to the conclusion that python packaging is horribly inflexible (and quite frankly broken). I'm pretty sure I could get it to work, but it doesn't seem worth the effort to do or maintain.

**Comment by fboender** [comment]
After much work and fighting with python packaging I've finally managed to make it work with the other packaged release forms, only to run into the fact that you're not allowed to re-upload a faulty package to PyPi (http://comments.gmane.org/gmane.comp.python.distutils.devel/22739)

Given the current horrible state of Python packaging, I've decided to not support any form of python packaging. As such, I won't be uploading packages to Pypi. I also won't accept any merge requests dealing with Python packaging.

**Comment by benkonrath** [comment]
Sorry to hear about your bad experience with setting up ansible-cmdb for pypi. There are definitely issues with Python packaging but things are better than they have been in the past. I personally haven't had the same negative experience as you so I'm not turned off the process.

Thanks for merging the setup.py (and for fixing the bug(s) in it :) ). This allows people who use pip to install with a github url so we're not cut off.

To me it makes sense that pypi doesn't allow you to re-upload a faulty package because you would be re-using the same version number for two different software releases. You see this pattern in most hosted software platforms: from CDNs to Linux distro packaging. The link you posted does actually have a solution for this particular problem but I guess you'd have to bump the minor version number (e.g. 1.6.1 or something).

We all really appreciate that you shared this very useful piece of software. Having ansible-cmdb on pypi has the potential to reach more users by allowing users to install it very quickly (i.e. `pip install ansible-cmdb`). But if you're not interested in dealing with pypi, that's definitely your choice to make. Thanks again for merging the setup.py.
