### ISSUE TITLE
ModuleNotFoundError: No module named 'ansiblecmdb'

### ISSUE THREAD

**Issue by pschonmann** [fboender/ansible-cmdb#233]
Hi i have problem to run ansible-cmdb
```
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 20, in <module>
    import ansiblecmdb
ModuleNotFoundError: No module named 'ansiblecmdb'
```
**Distro is Linux mint 20.1**

pip install ansible-cmdb gives me
```
Requirement already satisfied: ansible-cmdb in ./.local/lib/python3.8/site-packages (1.31)
Requirement already satisfied: ushlex in ./.local/lib/python3.8/site-packages (from ansible-cmdb) (0.99.1)
Requirement already satisfied: mako in ./.local/lib/python3.8/site-packages (from ansible-cmdb) (1.1.4)
Requirement already satisfied: jsonxs in ./.local/lib/python3.8/site-packages (from ansible-cmdb) (0.6)
Requirement already satisfied: pyyaml in ./.local/lib/python3.8/site-packages (from ansible-cmdb) (5.4.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.local/lib/python3.8/site-packages (from mako->ansible-cmdb) (2.0.1)
```

**Comment by fboender** [comment]
Is this still an issue or did you manage to fix it?

This usually happens when the environment being used to run ansible-cmdb is different than the one it was installed under. Ansible-cmdb uses a rather stupid wrapper script to find the "correct" python interpreter to use, but it sometimes gives the wrong result.

Have you tried the "fix" given in the Note in the [Getting Started](https://ansible-cmdb.readthedocs.io/en/latest/usage/#getting-started) chapter?

I'm planning on removing the entire wrapper and using Python setup's entry_points. There's a PR for it open I believe. That should fix this problem once and for all.

**Comment by pschonmann** [comment]
I fixed that. Thanks.
