### ISSUE TITLE
New column: public IP address

### ISSUE THREAD

**Issue by blondviper** [fboender/ansible-cmdb#234]
Hi, can you please add a new column that will display the public IP of the server?
Thank you

**Comment by fboender** [comment]
Hey blondviper!

Unfortunately it's not possible for *me* to do so, because Ansible itself doesn't supply the public IP as a host fact. However, you can do it yourself by creating custom facts for hosts that have the public IP.

Here's how we do that:

On each host we have a local fact that's a script that calls curl to get the external outgoing IP:

```
$ cat /etc/ansible/facts.d/ip.fact 
#!/bin/sh

curl --connect-timeout 2 --max-time 5 -sq 'https://api.ipify.org?format=json'
``` 

Output looks like this:

```
{"ip":"36.22.12.141"}
```

which appears in Ansible in the host facts under `ansible_facts.ansible_local.ip.ip`. So in our [custom columns definitions](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-columns) file, we have this:

```
    {
        "title": "External IP",
        "id": "ext_ip",
        "sType": "string",
        "visible": False,
        "tpl": """${ jsonxs(host, 'ansible_facts.ansible_local.ip.ip', default="") }"""
    },
```

Check the above linked documentation on more info about custom columns like these.

Hope that helps!
