### ISSUE TITLE
[html_fancy_split] Unable to sort custom column by mixed type "string"/ "num" AND how to custom template html_fancy_split

### ISSUE THREAD

**Issue by Kariton** [fboender/ansible-cmdb#235]
Hey folks, first of all: THANKS for such a great tool!

But somehow Im unable to sort by my custom culumn of `"sType": "num"`.

### ENV
CentOS 7
current ansible-cmd installed through pip
Webserver is NGINX - if that matters

### Description
I generate html files with the `html_fancy_split` template.

(see custom column conf below)
Im trying to filter by `Uptime`. In particular `Uptime [s]` which does... nothing.
No logs at all in browser console or webserver logs.

Filtering bei `Uptime` does work - string based as expectet. (1 Weeks, 11 Weeks, 111 Weeks, 2 Weeks, 22 Weeks, 222 Weeks and so on)
I also can filter on everything else. `vCPUs/ RAM [GiB]/ etc.`

 - What am I missing here?

### Custom configuration
`./custom.conf`
```
[
    {
        "title": "Uptime",
        "id": "uptime",
        "sType": "string",
        "visible": False,
        "tpl": """
          <ul>
            <%
            def ConvertSectoDay(n):
                weeks = n // (7 * 24 * 3600 )
                n = n % (7 * 24 * 3600)
                days = n // (24 * 3600)
                n = n % (24 * 3600)
                hours = n // 3600
                n %= 3600
                minutes = n // 60
                n %= 60
                seconds = n

                return("%d Weeks, %d Days, %d Hours, %d Minutes, %d Seconds" % (weeks, days, hours, minutes, seconds))

            uptime = ConvertSectoDay(int(jsonxs(host, 'ansible_facts.ansible_uptime_seconds', default=0)))
            %>
              <li>${uptime}</li>
          </ul>
        """
    },
    {
        "title": "Uptime [s]",
        "id": "uptime_s",
        "sType": "num",
        "visible": False,
        "tpl": """
          <ul>
            <%
            uptime_s = int(jsonxs(host, 'ansible_facts.ansible_uptime_seconds', default=0))
            %>
              <li>${uptime_s}</li>
          </ul>
        """
    },
]
```

### Command used
```
ansible-cmdb -t html_fancy_split -p collapsed=1 -C ./custom.conf
```
and then i move `./cmdb` to `/var/www/html/`

# Slightly off-topic
*(maybe i should create an other "issue"? - i dont have much experience with GitHub)*  
 - Is it possible to set a "sort helper" for custom columns like `Uptime` based on the seconds - to get it correctly sortet but easily human readable? - is a custom template required?
I noticed `## hidden sort helper` for `memory / swap / mounts / etc` - but dont know how to make use of it.
 - I dont understand how to create a custom `html_fancy_split` template at all. How do i make use of `html_fancy_split.py`?
 a "simple" custom template is well documented and straightforward with the provided templates as guideline.
 
 ### small (nice) edit i do on my template - change colors (example values)
*(unless i know how to build a custom `html_fancy_split` template)*
#### this may not work in future releases of `ansible-cmdb` - for obvious reasons.

```
echo "edit header color"
sed -i 's@0071b8@0090F0@g' /var/www/html/cmdb/*
```
Description: `0071b8` (first hex color value) is the "original" color - `0090F0` (second hex color value) is the "new" color
```
echo "edit text color"
sed -i 's@FFFFFF@000000@g' /var/www/html/cmdb/*

echo "edit clear settings button color"
sed -i 's@0090F0@0071b8@g' /var/www/html/cmdb/*

echo "edit unchecked filter button color"
sed -i 's@009688@FFFFFF@g' /var/www/html/cmdb/*

echo "edit checked filter button color"
sed -i 's@B0B0B0@009688@g' /var/www/html/cmdb/*
```

edit1: change color from `sed` to avoid "collisions"

**Comment by fboender** [comment]
Hi Kariton!

Glad you find ansible-cmdb useful. It's unfortunate that I have so little time to work on it.

>  Im trying to filter by Uptime. In particular Uptime [s] which does... nothing.

I suspect the issue is with the `<ul><li>` construction. You probably took that as an example from elsewhere, but you only need to do a list if there are multiple items per host, such as with disks. The `<ul><li>` elements tend to get in the way of numerical sorting though.

Try something like this:

```
    {
        "title": "Uptime [s]",
        "id": "uptime_s",
        "sType": "num",
        "visible": False,
        "tpl": """
            <%
            uptime_s = int(jsonxs(host, 'ansible_facts.ansible_uptime_seconds', default=0))
            %>
            ${uptime_s}
        """
    },
```

And in fact, if you use jsonxs, you shouldn't have to use the "tpl" type at all, but you can use the "jsonxs" method directly, like so:

```
    {
        "title": "Uptime [s]",
        "id": "uptime_s",
        "sType": "num",
        "visible": False,
        "jsonxs": "ansible_facts.ansible_uptime_seconds"
    },
```
> Is it possible to set a "sort helper" for custom columns like Uptime based on the seconds - to get it correctly sortet but easily human readable?

Sorting works pretty simply. It just sorts on the first value it encounters in the column of the table. So if we add a hidden value at the front of the column, it will sort on that. So that should be the computer-readable version. After that you can add any human-readable (and visible) content to actually show to the user.

For example:

```
      ## hidden sort helper
      <span style="display:none">${sort_used}</span>
      <span>${used} GiB</span>
```

Where `used` would be some nice human readable version like `12.14 GiB` and `sort_used` is the computer-readable and sortable value like `12140000000` (that's not actually 12.14 GiB but I was too lazy to calculate ;-) )

In particular, the `style="display:none"` is important, because it hides the real value that's sorted on from the user.

> I dont understand how to create a custom html_fancy_split template at all. How do i make use of html_fancy_split.py

Oh good question. The "html_fancy" template used to be a lot simpler and customizing it meant just copying two templates as mentioned in the [Custom Templates](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-templates) chapter of the documentation. It's gotten a little bit more intricate now. I had to test if the following actually works.

You can basically just copy all the `html_fancy*` files to a separate dir and then specify the `.py` file as your template:

```
# In the root dir of the ansible-cmdb git checkout
$ mkdir ~/Temp/mytpl
$ cp src/ansiblecmdb/data/tpl/html_fancy* ~/Temp/mytpl/
```

You can then generate it by just pointing the `-t` option to the `html_fancy_split.py

```
$ ansible-cmdb -t ~/Temp/mytpl/html_fancy_split.py -i hosts out/
```

the `html_fancy_split.py` script creates a `cmdb` dir and then generates the overview (sortable columns) using the `html_fancy_split_overview.tpl` template in the current dir and writes the output to the `cmdb/index.html` file. It then generates one HTML file in the `cmdb/` dir for each host using the `html_fancy_split_detail.tpl` template. Both the detail and overview templates make use of definitions from the `html_fancy_defs.html`, which they include. It has the column definitions, the CSS and HTML, etc. This is probably where you'd make any changes you'd like.

> small (nice) edit i do on my template - change colors (example values)

Yeah, that's pretty nice. I've had some requests for skinnability, like maybe custom CSS. I should look into that cause I'm sure people would like CMDB to have their company colors or whatever. At the moment you should be able to fully customize the CSS in the `html_fancy_defs.html` template under the `HTML Fragments` section:

```
##
## HTML fragments
##
<%def name="html_header(title, local_js, res_url)">
```
That should be a little bit more future-version friendly, although you'd miss out on changes in the official template; not that there are going to be much in the near future I think.

I guess all of this isn't very user-friendly, is it? :-) Ansible-cmdb used to be a very simple script of maybe a few dozen lines of code. It's grown into a bit of an unwieldy beast, which is one of the reasons I don't want to add big new functionalities to it.

Anyway, hope this helps and if you run into any more difficulties, don't hesitate to comment here. I'm going to look into updating the official documentation with some of the things discussed here cause it's gonna be useful to other people no doubt.

**Comment by Kariton** [comment]
Thanks for your awsome reply.  
Your tipp to just define `"jsonxs": "ansible_facts.ansible_uptime_seconds"` did the trick.

But did i understand this correctly?
`"tpl":` and `<ul><li>` is really needed for arrays that needs to get looped through - like the documented example for nameservers. for example.

If i need a single value i can just utilice `"jsonxs":`.

Cold you provide me an example for my particular "sort helper"?

im trying this now:
```
    {
        "title": "Uptime",
        "id": "uptime",
        "sType": "string",
        "visible": False,
        "tpl": """
          <%
          def ConvertSectoDay(n):
              weeks = n // (7 * 24 * 3600 )
              n = n % (7 * 24 * 3600)
              days = n // (24 * 3600)
              n = n % (24 * 3600)
              hours = n // 3600
              n %= 3600
              minutes = n // 60
              n %= 60
              seconds = n

              return("%d Weeks, %d Days, %d Hours, %d Minutes, %d Seconds" % (weeks, days, hours, minutes, seconds))

          sort_uptime = int(jsonxs(host, 'ansible_facts.ansible_uptime_seconds', default=0))
          uptime = ConvertSectoDay(int(jsonxs(host, 'ansible_facts.ansible_uptime_seconds', default=0)))
          %>
          ## hidden sort helper
          <span style="display:none">${sort_uptime}</span>
          <span>${uptime}</span>
        """
    },
```
which does not work as expected.
| Uptime                                             | Uptime [s] |
|----------------------------------------------------|------------|
| 0 Weeks, 0 Days, 0 Hours, 0 Minutes, 0 Seconds     |            |
| 16 Weeks, 3 Days, 21 Hours, 33 Minutes, 40 Seconds | 10013620   |
| 17 Weeks, 0 Days, 22 Hours, 53 Minutes, 24 Seconds | 10364004   |
| 18 Weeks, 0 Days, 23 Hours, 51 Minutes, 34 Seconds | 10972294   |
| 20 Weeks, 6 Days, 1 Hours, 56 Minutes, 56 Seconds  | 12621416   |
| 2 Weeks, 5 Days, 17 Hours, 42 Minutes, 35 Seconds  | 1705355    |
| 22 Weeks, 5 Days, 21 Hours, 46 Minutes, 32 Seconds | 13815992   |
| 0 Weeks, 0 Days, 4 Hours, 4 Minutes, 16 Seconds    | 	14656     |
| 28 Weeks, 2 Days, 1 Hours, 1 Minutes, 24 Seconds   | 	17110884  |


And sorting the other way around does not work ether.



Generating a custom `html_fancy_split` template is a task for another day. ;)

**Comment by fboender** [comment]
> But did i understand this correctly? "tpl": and <ul><li> is really needed for arrays that needs to get looped through - like the documented example for nameservers. for example.

Yeah, exactly. But in your example you had `${uptime_s}` (a single value; not a list) wrapped in a `<ul><li>`.

> im trying this now: [...] which does not work as expected

I *think* maybe you should change the sort type to "num" instead of "string"? Let me know if that fixes it. If not, I'll give it a closer look.

**Comment by Kariton** [comment]
> Yeah, exactly. But in your example you had ${uptime_s} (a single value; not a list) wrapped in a `<ul><li>`.

I initally didnt know that. ;)
But wanted to be clear to understand the need of `<ul><li>` correctly.

> I think maybe you should change the sort type to "num" instead of "string"? Let me know if that fixes it. If not, I'll give it a closer look.

Does not work ether. (sort does now nothing)
The problem seems to be the mixed type. I want to sort my `string` based on `integer / num`.
`10182127 16 Weeks, 5 Days, 20 Hours, 22 Minutes, 7 Seconds` is the raw row - without `display:none`

I would need to limit the `"sType"` to the first "split" `"num"` - or something.

**Comment by Kariton** [comment]
If this wouldnt be easily possible (or at all) - im fine by sorting through another row - `Uptime [s]` is right next to it.

But maybe it could become handy, for someone else or later me, to know how to mix things up - if it would be _really_ needed.

**Comment by fboender** [comment]
> Does not work ether. (sort does now nothing) The problem seems to be the mixed type.

Hm, too bad. The "Memory" column also has mixed types, but I can sort it just fine. I thought it would have worked with your use-case too. I didn't actually implement that myself, so I'm not sure how it manages mixed types and still be sortable.

Looks like it uses "string" as the sort type and then adds a hidden value that maps the mem usage (0% - 100%) to a range between 0.0 to 1.0.

The problem is probably that the string sorting thinks that, for example, "200" is larger than "1000" because "2" is larger than "1". That should be fixable by zero-padding the strings to something like "00200" and "01000".

For the uptime, that could look something like this:

```
>>> uptime = 1251701
>>> sort_uptime = "{0:012d}".format(uptime)
>>> print(sort_uptime)
000001251701
```

**Comment by fboender** [comment]
Nice! I'll keep this issue open so that I remember to add this information to the documentation.

**Comment by fboender** [comment]
I added documentation based on this issue for column sorting to the [Custom columns](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-columns) chapter of the manual.

Instructions on how to customize the `html_fancy_split` template have been added to the [Custom templates](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-templates) chapter.
