### ISSUE TITLE
Make clean git -i

### ISSUE THREAD

**Issue by rndmh3ro** [fboender/ansible-cmdb#25]
Hi Ferry!

when trying to build a release with the Makefile, the `git clean -i -d -x -f` fails because of missing `-i` in my git version (1.7.9.5).

`git -i` is interactive mode. Is this needed when building a release? I think make should run automatically.

**Comment by fboender** [comment]
Hey Sebastian,

For `make release`, the repo has to be clear of nearly everything (.pyc files, caching, generated example output, temp files, etc). A .gitignore won't help, since the package building process doesn't reference it. But if the `clean` rule is fully automatic, it might delete unstaged changes, which is the last thing I'd want. An automated build / release wouldn't have those files anyway (cause it wouldn't have been touched by humans), so the `git clean -i` won't raise any questions anyway.

Initially I had separate commands in the `clean` section to remove .pyc files, etc, but it took a bit too much maintenance and regularly screwed up test-released I'd make.

Perhaps we could do the following:

1. `make clean` automatically cleans only files generated by other Make rules.
2. `make release` refuses to work unless the repo is clean. This would remove the interactive aspect of the rule, but still prevent accidental deletion of unstaged changed.

**Comment by rndmh3ro** [comment]
Your suggestions sounds good!

Maybe use `git clean -n -d -x` to show what would/should be removed?

**Comment by fboender** [comment]
> Maybe use git clean -n -d -x to show what would/should be removed?

Looks good!

**Comment by fboender** [comment]
Fixed!

`make clean` now removes build / test artifacts. A new make target `release_clean` has been added which checks that the git repo is clean.
