### ISSUE TITLE
Error installing on Amazon AMI

### ISSUE THREAD

**Issue by garlandkr** [fboender/ansible-cmdb#4]
yum install ansible-cmdb*.rpm

```
Transaction check error:
  file / from install of ansible-cmdb-1.2-2.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
  file /usr/bin from install of ansible-cmdb-1.2-2.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
  file /usr/lib from install of ansible-cmdb-1.2-2.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
```

**Comment by fboender** [comment]
Hey Ken,

Thank you for the bug report!

Looks like an issue with the use of Alien to convert the .deb to the .rpm. I'll have to create a proper one. In the meantime you could probably use the .tar.gz install. 

I'll try to have this issue fixed as soon as possible.

Regards,

Ferry

**Comment by fboender** [comment]
I managed to reproduce this problem on Fedora 22. Amazon AMI uses a self-made hybrid distribution, but I think the fix for Fedora 22 should also have fixes the issue on Amazon AMI. If not, please re-open this bug report so I can have a further look.

I'll release a new version of ansible-cmdb today. This will include a fixed RPM.

Thank you for your bug report!
