### ISSUE TITLE
comparing hosts side-by-side

### ISSUE THREAD

**Issue by wmangano** [fboender/ansible-cmdb#60]
feature request:

- comparing 2+ servers side-by-side and highlight difference (nice compliance feature... i think)
- export/output markdown

**Comment by fboender** [comment]
Hey wmangano! 

Thanks for your feature requests. I've created a new feature request (#62) for "export/output markdown" so it's easier to track.

I'm afraid side-by-side diffing is going to be difficult to implement due to how ansible-cmdb is currently implemented. Basically all it does is gather all the data and send it to a template to render a static HTML page. Unfortunately, this doesn't make it very suitable for interactive stuff such as diffing data. I'd have to include the full JSON data for each host and implement some kind of diffing tool in javascript.

I suggest you use something like Meld. It works pretty great for showing differences between hosts:

    $ meld debian.dev.local zoltar.electricmonk.nl

![meld diff]
(http://www.electricmonk.nl/temp/ansible-meld.png)

**Comment by fboender** [comment]
Hi! 

The new v1.13 release includes a Markdown template. You can use it like so:

    ansible-cmdb -d -t markdown -i hosts out > cmdb.md

You may want to check out my [https://github.com/fboender/mdpreview](mdpreview) project to preview the generated markdown file ;-)
