### ISSUE TITLE
Feature Request: Dynamic Inventory

### ISSUE THREAD

**Issue by wmangano** [fboender/ansible-cmdb#77]
hi Ferry!
did you ever thought about extend ansible-cmdb to use it as a dynamic inventory?

For example:
----- mockup commandline ----
ansible-cmdb-cli --facts "vcpus >= 4"

output of this command is a json object listing all server with vcpu 4+. i think that would be a great feature. what do you think?

**Comment by fboender** [comment]
Hi wmangano!

It's an interesting idea. I have to wonder how useful it would be, since ansible-cmdb already gets all its information from other sources. The filtering would be interesting.

For now, unfortunately, it's a bit outside the scope of ansible-cmdb. I'm also quite busy, so implementing this is not something I'm willing to commit to at this point. I'll keep it in mind for the future though.

Thank you for your suggestion!
