### ISSUE TITLE
Make ansible-cmdb available on pip

### ISSUE THREAD

**Issue by zyv** [fboender/ansible-cmdb#90]
Hi there,

First off, I'd like to say that `ansible-cmdb` is really awesome. It allowed me to generate a very nice and useful overview out of my inventory in no time. Thank you very much for your work!

However, having that said, I find it difficult to install. As far as I can see, it's a pure-Python package, and it doesn't have much in terms of external dependencies. Nevertheless, I must download a Debian package and install it globally, or mess with a ZIP archive if I want to install it locally.

As a Python user, I'm expecting such applications to be available from pip, such that I could simply fetch it from there to install globally, locally, or in a virtualenv, and let it care of checking if my version is up to date, updating when necessary, etc.

Could you please properly package it and push to pip as an sdist or a wheel?

Many thanks!

**Comment by fboender** [comment]
Hi Yuri!

This is something that I initially intended to support, and which has been requested a few times. There's a discussion with more info in issue #83 

What it boils down to is that python packaging has some problems with static assets (jquery library and such) that make it difficult to create proper packages. I spent quite some time trying to get this right, but ultimately got frustrated with python packaging of a non-library tool. So I decided not to support it.

The current status is that I will accept pull requests that properly implement Pypi packaging (see the last comment on issue #83).

Since there seems to be a larger demand for this than I initially thought, I'm going to keep this ticket open and, depending on my available time, may implement this in the future.

**Comment by fboender** [comment]
After lots of frustration with Python packaging, ansible-cmdb can now be installed using Pip!

    sudo pip install ansible-cmdb

Currently it's not possible to install ansible-cmdb in a virtualenv. Please check the manual for additional instructions.

Thank you for the bug report!

**Comment by zyv** [comment]
Thanks a lot for putting the work into it, I will definitively test it soon at work!

In the mean time, would you mind elaborating on what's the problem with virtualenv? Maybe I and/or somebody else can help you fixing that.

(I'm not actually all too interested in a virtualenv install right now, what matters more to me is that `pip install --user` works correctly.)

**Comment by fboender** [comment]
There are a few different problems, the cause of which are not clear to me yet:

* There are permission problems with pip on MacOS that are not related to ansible-cmdb, but are well known in the MacOS community. The specific error is: `OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/ansiblecmdb'
2:serenity:/Users/cris> ansible-cmdb`, even though the user is using `sudo`.
* There are some problems in certain Python virtualenvs that try to install binaries globally, even though there is nothing globally defined in the setup.py.
* Installation in a Python v3 environment fails because it can't find the VERSION file in the build directory for some reason.

`pip install --user` seems to work for me, on my platform (Ubuntu 14.04), so maybe it'll work for you too.
